version: '3.4'
services:
  sayit-money-saver:
    privileged: true
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 8000:8000

  sayit-money-saver-db:
    image: postgres:15.7
    container_name: "sayit-money-saver-db"
    restart: always
    environment:
      POSTGRES_USER: wichen-admin
      POSTGRES_PASSWORD: wichenwichen-admin
      POSTGRES_DB: db
    ports:
      - "5440:5432"
    volumes:
      - /usr/local/sayit:/var/lib/postgresql/data
